---
# defaults file for parse_leapp_report
result_filename_prefix: /var/log/leapp/leapp-report
result_filename_json: "{{ result_filename_prefix }}.json"
result_filename_txt: "{{ result_filename_prefix }}.txt"
result_fact_cacheable: false
...
