---
- name: Delete snapshot
  amazon.aws.ec2_snapshot:
    snapshot_id: "{{ item.0 }}"
    region: "{{ ec2_region }}"
    state: absent
    wait: yes
  with_together:
    - "{{ snapshots_details.snapshots | map(attribute='snapshot_id') | list }}"
...
