---
# handlers file for logging
- name: Add end time to log file
  ansible.builtin.lineinfile:
    path: "{{ log_file }}"
    line: Job ended at {{ ansible_date_time.iso8601 }}
    owner: root
    group: root
    mode: '0644'
  listen: Archive log file

- name: Slurp ripu.log file
  ansible.builtin.slurp:
    src: "{{ log_file }}"
  register: ripu_log_file_slurp
  listen: Archive log file

- name: Decode ripu.log file
  ansible.builtin.set_fact:
    ripu_log_file: "{{ ripu_log_file_slurp.content | b64decode | split('\n') }}"
  listen: Archive log file

- name: Rename log file
  ansible.builtin.shell: |
    mv {{ log_file }} {{ log_file }}-{{ ansible_date_time.iso8601_basic_short }}
  listen: Archive log file
...
