---
- name: leapp_non_persistent_partitions | Add mount entry to /etc/fstab for non persistent /var/lib/leapp mount
  block:
    - name: leapp_non_persistent_partitions | Check if /var/lib/leapp exists in /etc/fstab
      ansible.builtin.command: grep /var/lib/leapp /etc/fstab
      register: fstab_output
      changed_when: false
      failed_when: fstab_output.rc not in [0, 1]

    - name: leapp_non_persistent_partitions | Continue when /var/lib/leapp is missing
      ansible.builtin.debug:
        msg: "/var/lib/leapp mount point not found. Skipping this task."
      when: fstab_output.rc == 1

    - name: leapp_non_persistent_partitions | Process remediation
      when: fstab_output.rc == 0
      block:
        - name: leapp_non_persistent_partitions | Get /var/lib/leapp mount device
          ansible.builtin.command: findmnt -nr -o SOURCE /var/lib/leapp
          register: mount_device_output
          changed_when: false

        - name: leapp_non_persistent_partitions | Get /var/lib/leapp mount filesystem type
          ansible.builtin.command: findmnt -nr -o FSTYPE /var/lib/leapp
          register: mount_filesystem_output
          changed_when: false

        - name: leapp_non_persistent_partitions | Get /var/lib/leapp mount options
          ansible.builtin.command: findmnt -nr -o OPTIONS /var/lib/leapp
          register: mount_options_output
          changed_when: false

        - name: leapp_non_persistent_partitions | Get UUID for the device
          ansible.builtin.command: blkid -s UUID -o value {{ mount_device_output.stdout }}
          register: uuid_output
          changed_when: false

        - name: leapp_non_persistent_partitions | Add /var/lib/leapp to /etc/fstab
          ansible.builtin.lineinfile:
            path: /etc/fstab
            line: UUID={{ uuid_output.stdout }} /var/lib/leapp {{ mount_filesystem_output.stdout }} {{ mount_options_output.stdout }} 0 0
          when:
            - "'/var/lib/leapp' not in fstab_output.stdout"
            - uuid_output.stdout is defined
            - mount_filesystem_output.stdout is defined
            - mount_options_output.stdout is defined

...
