---
- name: leapp_missing_yum_plugins | Continue when leapp report is missing
  ansible.builtin.debug:
    msg: "Leapp report missing. Skipping this task."
  when: leapp_report_missing | default(false)

- name: leapp_missing_yum_plugins | Load required plugins
  vars:
    entry_title_pattern: Required .* plugins are not being loaded.
    remediation_matches: "{{ leapp_report_data.entries | selectattr('title', 'match', entry_title_pattern) |
      map(attribute='detail.remediations') | flatten | list }}"
    remediation: "{{ remediation_matches | selectattr('type', 'eq', 'command') | first
      if remediation_matches | length > 0 else {} }}"
  when: not leapp_report_missing | default(false)
  block:
    - name: leapp_missing_yum_plugins | End execution of playbook if no entry found in leapp report
      ansible.builtin.debug:
        msg: "No matching entry found in leapp report. Skipping this task."
      when: remediation | length == 0

    - name: leapp_missing_yum_plugins | Output command to be executed
      ansible.builtin.debug:
        msg: remediation.context | join(' ')
      when: remediation | length > 0

    - name: leapp_missing_yum_plugins | Execute the remediation command - remove the deprecated directives from the sshd configuration
      ansible.builtin.command:
        argv: "{{ remediation.context }}"
      when: remediation | length > 0
      register: remediation_command_output
      changed_when: remediation_command_output is success

    - name: leapp_missing_yum_plugins | Show remediation command output
      ansible.builtin.debug:
        var: remediation_command_output.stdout_lines
...
