---
# TODO: Use ansible facts.
- name: check-for-old-packages | Search for old packages and packages not versioned by rhel release
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail;
      export PATH={{ os_path }};
      rpm -qa |
      grep -ve '[\.|+]el{{ ansible_distribution_major_version }}' |
      grep -vE '^(gpg-pubkey|libmodulemd|katello-ca-consumer)' |
      sort
  register: unsigned_packages_post
  changed_when: false
  failed_when:
    - unsigned_packages_post.rc != 0
    - unsigned_packages_post.stderr != ""

- name: check-for-old-packages | Set a fact that lists the old packages and packages not versioned by rhel release
  ansible.builtin.set_fact:
    unsigned_packages_post: "{{ unsigned_packages_post.stdout_lines }}"
    cacheable: true

- name: check-for-old-packages | Diff the list of current un-versioned packages and the previous list of un-versioned packages and set fact for missing packages
  ansible.builtin.set_fact:
    missing_non_rhel_packages: "{{ ansible_facts.ansible_local.non_rhel_packages | difference(unsigned_packages_post) }}"

- name: check-for-old-packages | Display warning message if there are any missing non-rhel versioned packages from the pre-upgrade
  ansible.builtin.debug:
    msg:
      - Warning!! There are non-rhel packages that were removed during the upgrade. Please review the list of missing packages
      - "{{ missing_non_rhel_packages }}"
  when: missing_non_rhel_packages | length >= 1

- name: check-for-old-packages | Save list of missing packages for future use/review
  ansible.builtin.copy:
    content: "{{ missing_non_rhel_packages }}"
    dest: /etc/ansible/facts.d/missing_packages.fact
    mode: "0644"
    owner: root
    group: root

- name: check-for-old-packages | Display results of search for old packages and packages not versioned by rhel release
  ansible.builtin.debug:
    msg: "{{ unsigned_packages_post }}"

- name: check-for-old-packages | Search for packages from previous os release, packages not versioned by rhel release and all dependent packages
  ansible.builtin.package:
    name: "{{ unsigned_packages_post }}"
    state: absent
  check_mode: true
  register: search_packages_result

- name: check-for-old-packages | Display results of the search for packages from the previous os release, packages not versioned by rhel release and all dependent
    packages
  ansible.builtin.debug:
    msg: "{{ search_packages_result.changes.removed | default(search_packages_result.results) | default([]) | regex_replace('Removed: ', '') }}"

...
