---
# TODO: Having issues with community.general.redhat_subscription and subscription-manager on RHEL 6.
- name: redhat-upgrade-tool-post-upgrade | Ensure redhat-upgrade-cmdline-instrepo.repo file is absent
  ansible.builtin.file:
    path: /etc/yum.repos.d/redhat-upgrade-cmdline-instrepo.repo
    state: absent

- name: redhat-upgrade-tool-post-upgrade | "Register to post upgrade activation key"
  ansible.builtin.shell: >
    export PATH={{ os_path }};
    subscription-manager register
    --org="{{ satellite_organization }}"
    --activationkey="{{ satellite_activation_key_post_leapp }}"
    --force
  register: sub_man_reg
  when:
    - leapp_upgrade_type == 'satellite'
    - satellite_organization is defined
    - satellite_activation_key_post_leapp is defined
  failed_when: false
  changed_when: true

- name: redhat-upgrade-tool-post-upgrade | Include custom_local_repos for local_repos_post_upgrade
  vars:
    __repos: "{{ local_repos_post_upgrade }}"
  ansible.builtin.include_role:
    name: infra.leapp.common
    tasks_from: custom_local_repos
  when: leapp_upgrade_type == "custom"

- name: redhat-upgrade-tool-post-upgrade | Include check-for-old-packages.yml
  ansible.builtin.include_tasks: check-for-old-packages.yml

- name: redhat-upgrade-tool-post-upgrade | Include grub2-upgrade.yml
  ansible.builtin.include_tasks: grub2-upgrade.yml
  when:
    - ansible_architecture == 'x86_64'
    - update_grub_to_grub_2

- name: redhat-upgrade-tool-post-upgrade | Include update-and-reboot.yml
  ansible.builtin.include_tasks: update-and-reboot.yml
...
