---
# defaults file for remedations

leapp_report_location: /var/log/leapp/leapp-report.json
remediation_playbooks:
  - LEAPP_CIFS_DETECTED
  - LEAPP_CORRUPTED_GRUBENV_FILE
  - LEAPP_CUSTOM_NETWORK_SCRIPTS_DETECTED
  - LEAPP_DEPRECATED_SSHD_DIRECTIVE
  - LEAPP_FIREWALLD_ALLOWZONEDRIFTING
  - LEAPP_FIREWALLD_UNSUPPORTED_TFTP_CLIENT
  - LEAPP_LOADED_REMOVED_KERNEL_DRIVERS
  - LEAPP_MISSING_EFIBOOTMGR
  - LEAPP_MISSING_PKG
  - LEAPP_MISSING_YUM_PLUGINS
  - LEAPP_MULTIPLE_KERNELS
  - LEAPP_NEWEST_KERNEL_NOT_IN_USE
  - LEAPP_NFS_DETECTED
  - LEAPP_NON_PERSISTENT_PARTITIONS
  - LEAPP_NON_STANDARD_OPENSSL_CONFIG
  - LEAPP_OLD_POSTGRESQL_DATA
  - LEAPP_PARTITIONS_WITH_NOEXEC
  - LEAPP_RELATIVE_SYMLINKS
  - LEAPP_RPMS_WITH_RSA_SHA1_DETECTED
  - LEAPP_UNAVAILABLE_KDE
  - LEAPP_VDO_CHECK_NEEDED
remediation_todo: []
...
