---
__leapp_logs_name: ansible_leapp_analysis
__leapp_reports_controller_dir: "{{ leapp_workdir_controller }}/{{ __leapp_logs_name }}_logs_{{ __leapp_timestamp }}"
__leapp_reports_dir: /var/log/leapp
__leapp_log_file_basename: "{{ __leapp_logs_name }}.log"
__leapp_log_file: "{{ __leapp_reports_dir }}/{{ __leapp_log_file_basename }}"
__leapp_report_json: "{{ __leapp_reports_dir }}/leapp-report.json"
__leapp_report_txt: "{{ __leapp_reports_dir }}/leapp-report.txt"

# Maps the title attribute of an inhibitor from a report to a remediation task file name
__leapp_inhibitors_title_map:
  "cgroups-v1 enabled on the system": leapp_cgroups-v1_enabled
  "Use of CIFS detected. Upgrade can't proceed": leapp_cifs_detected
  "Detected a corrupted grubenv file": leapp_corrupted_grubenv_file
  "custom network-scripts detected": leapp_custom_network_scripts_detected
  "A deprecated directive in the sshd configuration": leapp_deprecated_sshd_directive
  "Firewalld Configuration AllowZoneDrifting Is Unsupported": leapp_firewalld_allowzonedrifting
  "Firewalld Service tftp-client Is Unsupported": leapp_firewalld_unsupported_tftp_client
  "Legacy network configuration found": leapp_legacy_network_configuration
  "Leapp detected loaded kernel drivers which have been removed in RHEL 8. Upgrade cannot proceed.": leapp_loaded_removed_kernel_drivers
  "Leapp detected loaded kernel drivers which have been removed in RHEL 9. Upgrade cannot proceed.": leapp_loaded_removed_kernel_drivers
  "Leapp detected loaded kernel drivers which have been removed in RHEL 10. Upgrade cannot proceed.": leapp_loaded_removed_kernel_drivers
  "efibootmgr package is required on EFI systems": leapp_missing_efibootmgr
  "Package \"leapp-rhui-aws\" is missing": leapp_missing_pkg
  "Package \"leapp-rhui-google\" is missing": leapp_missing_pkg
  "Package \"leapp-rhui-azure\" is missing": leapp_missing_pkg
  "Package \"leapp-rhui-aws\" is not installed": leapp_missing_pkg
  "Package \"leapp-rhui-google\" is not installed": leapp_missing_pkg
  "Package \"leapp-rhui-azure\" is not installed": leapp_missing_pkg
  "Required DNF plugins are not being loaded.": leapp_missing_yum_plugins
  "Required YUM plugins are not being loaded.": leapp_missing_yum_plugins
  "Multiple kernels installed": leapp_multiple_kernels
  "Newest installed kernel not in use": leapp_newest_kernel_not_in_use
  "Use of NFS detected. Upgrade can't proceed": leapp_nfs_detected
  "Detected partitions mounted in a non-persistent fashion, preventing a successful in-place upgrade.": leapp_non_persistent_partitions
  "Non-standard configuration of openssl.cnf": leapp_non_standard_openssl_config
  "Old PostgreSQL data found in /var/lib/pgsql/data": leapp_old_postgresql_data
  "The pam_tally2 pam module(s) no longer available": leapp_pam_tally2
  "Detected partitions mounted with the \"noexec\" option, preventing a successful in-place upgrade.": leapp_partitions_with_noexec
  "Upgrade requires links in root directory to be relative": leapp_relative_symlinks
  "Possible problems with remote login using root account": leapp_remote_using_root
  "Detected RPMs with RSA/SHA1 signature": leapp_rpms_with_rsa_sha1_detected
  "The installed KDE environment is unavailable on RHEL 8": leapp_unavailable_kde
  "Cannot perform the VDO check of block devices": leapp_vdo_check_needed

# Maps the key attribute of an inhibitor from a report to a remediation task file name
__leapp_inhibitors_key_map:
  4d9174ec75e27f2713b672d8932a06ebaa84dfb3: leapp_cgroups-v1_enabled
  d0e1aa3f7c4fc4450bdcb9a27f47ff464d6af24a: leapp_cifs_detected
  f32345b6140b5a318c1c01e1cbc6ef1c0321e04a: leapp_corrupted_grubenv_file
  eb998ef774a556a501665fc811e72c5241dba076: leapp_custom_network_scripts_detected
  3d56089671c82f32874d89cbf0a95f828aae446a: leapp_deprecated_sshd_directive
  5b1cf050e1a877b0358b6e8c612277c591d40c13: leapp_firewalld_allowzonedrifting
  1d169a613d494a966c9b76c48ab0aef1626f5ac9: leapp_firewalld_unsupported_tftp_client
  7de70b43c3c9d20075e30894ac24a4c4e2d70837: leapp_legacy_network_configuration
  f08a07da902958defa4f5c2699fae9ec2eb67c5b: leapp_loaded_removed_kernel_drivers
  7ae2961239eec9905e2580fa6309a589b1dca953: leapp_loaded_removed_kernel_drivers
  48e04852631245aa4afee9adcdc7c2375b8cffb8: leapp_loaded_removed_kernel_drivers
  e2598a162267006cdc4340affef8603d731e34fa: leapp_missing_efibootmgr
  75c945f6ed19532e7d493bafedeb1b82e44750c5: leapp_missing_pkg
  eb93636a777abb26c2598cf10217cde9fa4733ed: leapp_missing_pkg
  a89d1f95ff6cc1ead9df3c974cce08985d20df98: leapp_missing_pkg
  cc99dc8eef25c09da6b5485ed0afde1252322756: leapp_missing_pkg
  220d7a9bdee78a75bbd8ca6aa347c98e50d4da41: leapp_missing_pkg
  8ca582fba112a46fbcd48cb660074b71ea554950: leapp_missing_pkg
  2a0ff91bea885cfe9d763cf3a379789848a501b9: leapp_missing_yum_plugins
  71269f4561e4fe1499aa87628ece79c607aedeca: leapp_missing_yum_plugins
  24eca9f4d355173d38ccf99f099a16fc84f243d7: leapp_multiple_kernels
  ebb478cfa5443f83a8c9a78ba510eb40e6e9d117: leapp_newest_kernel_not_in_use
  9881b25faceeeaa7a6478bcdac29afd7f6baaaed: leapp_nfs_detected
  1dbb140bcc2a78097d2109e4ff2bddea5599f9b6: leapp_non_persistent_partitions
  939963e62fa05512266f8a6f67dddad982a4252d: leapp_non_standard_openssl_config
  d10f8ee9e6bc4b73daff9c33671d1516136d53d8: leapp_old_postgresql_data
  ce6abfb001da076686ffdd4ab61d28eb12d12569: leapp_pam_tally2
  981b3e9e95ccdfab3d4c83c591d8082596aca1ad: leapp_partitions_with_noexec
  3d895ad37ceaf4157864d439edb6bd75562061fa: leapp_relative_symlinks
  3d21e8cc9e1c09dc60429de7716165787e99515f: leapp_remote_using_root
  f16f40f49c2329a2691c0801b94d31b6b3d4f876: leapp_rpms_with_rsa_sha1_detected
  4bada539189b239213b653dae48c383d20dfe97a: leapp_unavailable_kde
  429a99e13b19a7eebadbb8cb35233d8119bcf255: leapp_vdo_check_needed

...
