---
- name: analysis-leapp | Register to leapp activation key
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ leapp_satellite_activation_key_leapp }}"
    org_id: "{{ leapp_satellite_organization }}"
    force_register: true
  notify: Register to pre leapp activation key
  when:
    - leapp_upgrade_type == 'satellite'
    - leapp_satellite_organization is not none
    - leapp_satellite_activation_key_leapp is not none

- name: analysis-leapp | Include custom_local_repos for local_repos_pre_leapp
  vars:
    __repos: "{{ leapp_local_repos_pre }}"
  ansible.builtin.include_role:
    name: infra.leapp.common
    tasks_from: custom_local_repos
  when: leapp_upgrade_type == "custom"

- name: analysis-leapp | Install packages for preupgrade analysis on RHEL 7
  ansible.builtin.package:
    name: "{{ leapp_analysis_packages_el7 }}"
    enablerepo: "{{ leapp_analysis_repos_el7 }}"
    state: latest # noqa package-latest
  when: ansible_facts["distribution_major_version"]|int == 7

- name: analysis-leapp | Install packages for preupgrade analysis on RHEL 8
  ansible.builtin.package:
    name: "{{ leapp_analysis_packages_el8 }}"
    enablerepo: "{{ leapp_analysis_repos_el8 }}"
    state: latest # noqa package-latest
  when: ansible_facts["distribution_major_version"]|int == 8

- name: analysis-leapp | Install packages for preupgrade analysis on RHEL 9
  ansible.builtin.package:
    name: "{{ leapp_analysis_packages_el9 }}"
    enablerepo: "{{ leapp_analysis_repos_el9 }}"
    state: latest # noqa package-latest
  when: ansible_facts["distribution_major_version"]|int == 9

- name: analysis-leapp | Ensure leapp log directory exists
  ansible.builtin.file:
    path: /var/log/leapp
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: analysis-leapp | Populate leapp_answers file
  ansible.builtin.copy:
    content: "{{ leapp_answerfile }}"
    dest: /var/log/leapp/answerfile
    owner: root
    group: root
    mode: "0644"
  when: leapp_answerfile is defined

- name: analysis-leapp | Create /etc/leapp/files/leapp_upgrade_repositories.repo
  vars:
    __repos: "{{ leapp_local_repos }}"
    __leapp_repo_file: /etc/leapp/files/leapp_upgrade_repositories
  ansible.builtin.include_role:
    name: infra.leapp.common
    tasks_from: custom_local_repos
  when:
    - leapp_upgrade_type == 'custom'
    - leapp_local_repos | length > 0

- name: analysis-leapp | Leapp preupgrade report
  ansible.builtin.shell: >
    set -o pipefail;
    export PATH={{ leapp_os_path }};
    ulimit -n 16384;
    leapp preupgrade --report-schema=1.2.0
    {{ leapp_preupg_opts }}
    {{ __leapp_enable_repos_args }}
    2>&1 | tee -a {{ leapp_log_file }}
  environment: "{{ leapp_env_vars }}"
  changed_when: true
  register: leapp
  args:
    executable: /bin/bash
  async: "{{ leapp_async_timeout_maximum | int }}"
  poll: "{{ leapp_async_poll_interval | int }}"
  failed_when: "'report has been generated' not in leapp.stdout"

- name: analysis-leapp | Include custom_local_repos for local_repos_post_analysis
  vars:
    __repos: "{{ leapp_local_repos_post_analysis }}"
  ansible.builtin.include_role:
    name: infra.leapp.common
    tasks_from: custom_local_repos
  when: leapp_upgrade_type == "custom"

- name: analysis-leapp | Include check-results-file.yml
  ansible.builtin.include_tasks: check-results-file.yml

- name: analysis-leapp | Run parse_leapp_report to check for inhibitors
  ansible.builtin.include_role:
    name: infra.leapp.common
    tasks_from: parse_leapp_report.yml

...
