---
- name: check-results-file | Result file status
  ansible.builtin.stat:
    path: "{{ __leapp_report_txt }}"
  register: result

- name: check-results-file | Check that result file exists
  ansible.builtin.assert:
    that: result.stat.exists
    msg: The preupgrade analysis report file {{ __leapp_report_txt }} was not created.

...
