---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Release

on:
  release:
    types:
      - published

jobs:
  pre-commit:
    uses: oamg/ansible-leapp/.github/workflows/pre-commit.yml@main
  sanity:
    uses: oamg/ansible-leapp/.github/workflows/ansible-test.yml@main
  prechecks:
    needs:
      - pre-commit
      - sanity
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.pre-commit.result }}',
          '${{ needs.sanity.result }}',
          ]) == {'success'}"
  infra_release:
    needs:
      - prechecks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install --upgrade ansible-core

      - name: Update version in galaxy.yml
        run: sed -i 's/version:/version:{{:dumb_space_issue:}}${{ github.ref_name }}/' galaxy.yml; sed -i 's/{{:dumb_space_issue:}}/ /' galaxy.yml

      - name: Build collection
        run: ansible-galaxy collection build -vvv
        shell: bash
        working-directory: ${{ vars.GITHUB_PATH }}

      - name: Get tar name
        run: echo "tar_file=$(ls | grep '.tar')" >> $GITHUB_OUTPUT
        id: build

      - name: Get version
        run: echo "NUM=$(cat galaxy.yml | grep version | cut -d ':' -f 2 | awk '{print $1}')" >> $GITHUB_OUTPUT
        id: vers

      - name: Install collection
        run: ansible-galaxy collection install ./infra-leapp-${{ steps.vers.outputs.NUM }}.tar.gz -p /home/runner/collections
        shell: bash
        working-directory: ${{ vars.GITHUB_PATH }}

      - name: Publish to galaxy
        run: ansible-galaxy collection publish --api-key=${{ secrets.GALAXY_INFRA_KEY }} ${{ steps.build.outputs.tar_file }}

      - name: Upload files to tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.build.outputs.tar_file }}
          tag: ${{ github.ref }}
          overwrite: true
  changelog:
    needs:
      - infra_release
    runs-on: ubuntu-latest
    env:
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install --upgrade ansible-core antsibull-changelog

      - name: Update version in galaxy.yml
        run: sed -i 's/version:/version:{{:dumb_space_issue:}}${{ github.ref_name }}/' galaxy.yml; sed -i 's/{{:dumb_space_issue:}}/ /' galaxy.yml

      - name: Run changelog
        run: antsibull-changelog release --verbose --version ${{ github.ref }}

      - name: Create Pull Request
        id: prcreate
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update changelog ${{ github.ref }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: devel
          branch: changelog-patches
          delete-branch: true
          title: '[RELEASE] Update changelog ${{ github.ref }}'
          body: |
            Update changelog
            - Updated with changelog for release ${{ github.ref }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            changelog
            automated pr
          draft: false
...
